# Generated by Django 5.2.16 on 2026-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_required', models.TextField(help_text='e.g. Python, Django, SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
